### ISSUE TITLE
ClassFormatError In Obfuscated JAR (Using String Literal Mutator)

### ISSUE THREAD

**Issue by CadeCodes** [sim0n/Caesium#20]
Whilst not using the string literal mutator, I can create an obfuscated jar that runs as expected. Although, when I enable this mutator (which is essential to the software I am trying to obfuscate) I get a class format error with one of IntelliJ's UI designer classes. I created this app in IntelliJ using their java swing designer and it runs fine on java 8 with no obfuscation. Adding the "forms_rt" redist jar to the dependencies did not help.

-I am using the latest release of Caesium, and JDK 1.8.0_281.
The full error is below:

Exception in thread "main" java.lang.ClassFormatError: Class file version does not support constant tag 15 in class file com/intellij/uiDesigner/core/GridLayoutManager
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by CadeCodes** [comment]
IntelliJ Redist Issue
